name: Compile

on: [push, pull_request]

jobs:
  run_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Install pandoc
        run: sudo apt-get install  pandoc texlive-latex-recommended texlive-xetex texlive-luatex pandoc-citeproc texlive-latex-extra context wkhtmltopdf librsvg2-bin groff ghc nodejs python2
            libjs-mathjax libjs-katex citation-style-language-styles
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile document with pandoc
        run: |
          pandoc chronologie_teil1.md -o chronologie_teil1.pdf
      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: chronologie_teil1.pdf
          path: chronologie_teil1.pdf
